# Generated by Django 5.2.7 on 2025-11-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={},
        ),
        migrations.AddConstraint(
            model_name='accounts',
            constraint=models.UniqueConstraint(condition=models.Q(('username__isnull', False)), fields=('username',), name='unique_non_null_username'),
        ),
    ]
