# Generated by Django 5.2.7 on 2025-11-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_accounts_unique_non_null_username_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accounts',
            name='unique_username_when_not_null',
        ),
        migrations.AddField(
            model_name='accounts',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='accounts',
            constraint=models.UniqueConstraint(condition=models.Q(('display_name__isnull', False)), fields=('display_name',), name='unique_display_name_when_not_null'),
        ),
    ]
